Added ParaGraph logger support
ssnetsim/supersim pull request #48
Opened 2021-11-15 16:05 UTC by michael-isaev

2021-11-15 18:53 UTC, nicmcd requested changes

2021-11-15 18:53 UTC, nicmcd commented on src/workload/paragraph/GraphTerminal.cc
> +  CHECK_OK_AND_ASSIGN(
Add `"log_file": "graph.%d.csv"` to config/ring_iq_paragraph.json so that this functionality is at least exercised in the examples.

2022-01-20 23:23 UTC, nicmcd commented
@michael-isaev ping!

2022-05-19 20:26 UTC, michael-isaev commented
Finally updated, @nicmcd PTAL

2022-05-20 20:41 UTC, merged